[package]
name = "rust-github-webhook-reciever"
authors = ["Ron Mallory <ronnymallory@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.1"
env_logger = "0.10.1"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
